### ISSUE TITLE
Training times/license

### ISSUE THREAD

**Issue by cgallik** [wanmeihuali/taichi_3d_gaussian_splatting#115]
Hello,

I was wondering, how much slower are the training times than the official implementation? I am currently running your implementation and it seems significantly slower.

The other question, is the license. This is under Apache 2.0, which allows for commercial use, but official implementation does not allow this. Why the difference?

Thank you for your work!

**Comment by wanmeihuali** [comment]
I think it's 2-3 times slower in training and 2 times slower in inference. The reason is most likely to be some limitation of taichi, e.g. not support float4. If you notice any other fix that can accelerate the code, contributions are welcome.
For license, the code is developed based on their paper only and released one month before the official code. For the same reason there might be any detail differences between two implementations which could cause the difference in speed.
