### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by hardikdava** [wanmeihuali/taichi_3d_gaussian_splatting#116]
Thank you for your amazing work. I have 2 questions regarding visualization.

- Is there anyway to visualize `.parquet` file with any web-based viewer or locally cpu-based machine? 
- Is it possible to convert `.parquet` to some another known point cloud or mesh format?

**Comment by wanmeihuali** [comment]
Web visualizer based on vulkan is in future plans, but not available for now. I'm still trying to implement the radix sort by taichi, but meet some problem for int64 support.
The parquet file is just a pandas table, the columns are very straightforward. You can just take the x,y,z,alpha columns to build any point cloud file. However, most of the points in the point cloud are almost transparent, I've tried to build mesh by the point cloud but the result is not very good. Maybe MarchCube method still works, but it requires a lot more code.

**Comment by hardikdava** [comment]
@wanmeihuali Thanks for your reply. I was able to extract pointcloud from `.parquet` file. Is there anyway to get textured mesh output? Like converting feature vectors to meaningful RGB values?

**Comment by wanmeihuali** [comment]
@hardikdava 
Currently, there isn't an efficient way to obtain a textured mesh output. The difficulties stem from two aspects:

You might have noticed that the alpha value in the parquet represents the opacity of each point. Algorithms like the one used here, akin to NeRF, assume all 3D objects are semi-transparent and render them through volume rendering. The issue arising from this is that, unlike traditional point clouds where points are distributed on the surface of objects, the point cloud generated by this algorithm contains numerous near-transparent points distributed near the surface of objects. The color stacking of these points accurately portrays the surface of the object. Conventional point-cloud-to-mesh algorithms struggle with this scenario, often not taking into account the opacity of the points at all. My previous experiments in this area haven't been very successful. You might need a customized point-cloud-to-mesh conversion algorithm.

Even if you manage to extract a mesh from this point cloud, obtaining the corresponding colors remains imprecise. This is because the current algorithm employs spherical harmonic functions to represent colors, meaning that the color of the same point changes depending on the camera angle. For approximate color values, I would suggest referring to the r_sh0, g_sh0, and b_sh0 columns, taking the sigmoid of each, and then mapping the result to an integer between 0 to 255. Though this color estimation may not be entirely accurate, it shouldn't be too far off.
```math

(r', g', b')=(sigmoid(r_sh0), sigmoid(g_sh0), sigmoid(b_sh0))\times 255
```

**Comment by wanmeihuali** [comment]
@hardikdava  It should be possible, but you might need to modify the color computing formula by adding a sigmoid after the SH function.

**Comment by YertleTurtleGit** [comment]
```python
import pandas as pd
from plyfile import PlyData, PlyElement
import numpy as np
from pathlib import Path


def convert_parquet_to_ply(parquet_file_path: Path):
    MAPPING = {
        "cov_q0": "rot_0",
        "cov_q1": "rot_1",
        "cov_q2": "rot_2",
        "cov_q3": "rot_3",
        "cov_s0": "scale_0",
        "cov_s1": "scale_1",
        "cov_s2": "scale_2",
        "alpha0": "opacity",
        "r_sh0": "f_dc_0",
        "g_sh0": "f_dc_1",
        "b_sh0": "f_dc_2",
    }
    SH_CO = 0.28209479177387814

    ply_file_path = parquet_file_path.with_suffix(".ply")

    data_frame = pd.read_parquet(parquet_file_path, engine="pyarrow")
    data = data_frame.to_numpy()
    columns = data_frame.columns
    features = list(data_frame.columns)

    def get_feature_columns(feature_names):
        return [columns.get_loc(feature_name) for feature_name in feature_names]

    data[:, get_feature_columns(["r_sh0", "g_sh0", "b_sh0"])] *= SH_CO

    data[:, get_feature_columns(["cov_q0", "cov_q1", "cov_q2", "cov_q3"])] = data[
        :, get_feature_columns(["cov_q3", "cov_q0", "cov_q1", "cov_q2"])
    ]

    features = [MAPPING.get(feature, feature) for feature in features]

    dtype_full = [(feature, "f4") for feature in features]
    elements = np.empty(data.shape[0], dtype=dtype_full)
    elements[:] = list(map(tuple, data))
    elements = PlyElement.describe(elements, "vertex")
    PlyData([elements]).write(ply_file_path)


convert_parquet_to_ply(Path("my_splat.parquet"))
```
