### ISSUE TITLE
what conic means

### ISSUE THREAD

**Issue by llianxu** [wanmeihuali/taichi_3d_gaussian_splatting#117]
Hi !
It is an amazing work !
I noticed that you've used **"conic"** in many places in your code. I would like to understand the reasons for using **"conic"** and find some resources to help me comprehend why **"conic"** is used. Thank you.

**Comment by kwea123** [comment]
it's the inverse of the (projected) 2D covariance matrix, it is really confusing that the original authors use this variable name

**Comment by wanmeihuali** [comment]
@kwea123 is correct, it's a pre-compute value for each point. A little background here is that each point affects multiple pixels, so it's a bit faster to do computations on the point level rather than the pixel level, and using "conic" instead of covariance in the pixel level does slightly improve the inference speed. It is an optimization "borrow" from the official repo, and I have no idea why they call it conic...
