### ISSUE TITLE
Provide dataset

### ISSUE THREAD

**Issue by YoannSo** [wanmeihuali/taichi_3d_gaussian_splatting#62]
Hi ! 
Its an amazing work ! 
Can you provide some compatible dataset to test your program first ? 
thanks a lot

**Comment by wanmeihuali** [comment]
@YoannSo Thanks!
For the test, I'm using the tank and temple dataset(truck). See the link here: https://www.tanksandtemples.org/download/
I'm not sure if I can provide an extra download link due to the license. 
then you can first use colmap to generate a sparse reconstruction, then save it as txt and use this [file](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/blob/main/tools/prepare_colmap.py) to generate the two json files.

I can provide your with the generated two JSON files, but you may need to download the images separately.

**Comment by YoannSo** [comment]
Yes, if you can I'd love to have the json files you've generated thank you!

**Comment by wanmeihuali** [comment]
@YoannSo Here it is: https://github.com/wanmeihuali/taichi_3d_gaussian_splatting#train-on-tank-and-temple-truck-scene

**Comment by YoannSo** [comment]
thanks !

**Comment by YoannSo** [comment]
Hi, i have one error when trainning, 
![image](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/assets/58392344/c3e68bbb-6e03-404f-81c6-470a9ba3c79e)
maybe something is deprecated on my project ? Im running this in unbuntu and cuda 11.4 with torch 1.12.1
Thanks for your help

**Comment by wanmeihuali** [comment]
@YoannSo  Emm interesting, my environment is CUDA12.1+torch2.0, and it doesn't have such issue... one possible problem is that point_id_in_camera_list is defined as int32, can you try converting it to long? e.g.
```python
self.accumulated_num_in_camera[input_data.point_id_in_camera_list.long()] += 1
```
maybe int32 type tensor is not supported as index in earlier version?

**Comment by YoannSo** [comment]
thanks, already tried this on all variable and i got this error futher 
![image](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/assets/58392344/923ffd8e-422d-4f07-adc4-f4dea4d16007)
![image](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/assets/58392344/2cd0beee-4d6c-494c-bdb8-79d4544243ca)

**Comment by wanmeihuali** [comment]
Seems still a problem related to data type? You can try commenting self._plot_grad_histogram out, it's just a logging function for tensorboard that plot gradient distribution, I guess may be it's because the earlier version of torch/tensorboard does not have good support for int32....

**Comment by YoannSo** [comment]
Ok that's work correctly now, thanks !
